repos:
  - repo: local
    hooks:
      - id: make-format-modules
        name: Make Format Modules
        entry: make format-modules
        language: system
        stages: [commit]
        always_run: true
      - id: build-packages
        name: Build Packages
        entry: make build
        language: system
        stages: [ commit ]
        always_run: true